FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-run

# Defines our working directory in container
WORKDIR /usr/src/app

# install required packages
RUN JOBS=MAX npm install --unsafe-perm --production -g http-server

# Move app to filesystem
COPY ./app ./

# Start app
CMD ["bash", "/usr/src/app/start.sh"]
